import { noul } from '@typesafe-ai/sdk';

/** Stay well under Jev's 32k-token state budget. */
export const MAX_POST_CHARS = 8000;

export const JEV_MODEL = 'jev-1.13.0';

export type JevState = {
  postText: string;
};

/**
 * Jev is not generative. This only defines a typed question;
 * the model returns a calibrated probability, never prose.
 */
export function buildQuestions() {
  return {
    // Noul = yes/no probability in [0, 1].
    isSlop: noul(
      'Is this post AI slop: low-effort text generated by an AI model, rather than useful writing by a human?',
      {
        true: 'Generic AI-generated filler: template structure, buzzwords, empty engagement bait, listicle or hedged phrasing, no personal specifics.',
        false: 'Written by a human: a specific, personal, or informal voice, or it gives real information or insight.',
      },
    ),
  };
}

export function buildState(text: string): JevState {
  const postText =
    text.length > MAX_POST_CHARS ? `${text.slice(0, MAX_POST_CHARS)}…` : text;
  return { postText };
}
